services:
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
      - api
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - anaconda_net
    env_file:
      - ../.env

  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - anaconda_net
    env_file:
      - ../.env

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    expose:
      - "8000"
    networks:
      - anaconda_net
    env_file:
      - ../.env

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - anaconda_net
    env_file:
      - ../.env

  redis:
    image: redis:7-alpine
    networks:
      - anaconda_net
    env_file:
      - ../.env

networks:
  anaconda_net:
    name: anaconda_net

volumes:
  postgres_data:
    name: anaconda_postgres_data
